{% set info = load_file_data("wxvx/resources/info.json") %}
{% set pymin = "3.10" %}

package:
  name: wxvx
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - python {{ pymin }}
    - setuptools
  run:
    - iotaa >=1.2.0
    - met2go 11.0.*
    - netcdf4 >=1.7,<2
    - pyproj 3.7.*
    - python >={{ pymin }}
    - pyyaml 6.*
    - requests >=2.32,<3
    - uwtools 2.7.*
    - xarray >=2023.12
    - zarr >=2.17,<3
test:
  requires:
    - docformatter 1.7.*
    - jq 1.7.*
    - make 4.4.*
    - mypy 1.14.*
    - pyfakefs 5.7.*
    - pytest 8.3.*
    - pytest-cov 6.0.*
    - pytest-xdist 3.6.*
    - python {{ pymin }}
    - ruff 0.9.*
about:
  license: APACHE
