{% set info = load_file_data("wxvx/resources/info.json") %}
{% set python = "python 3.13" %}

package:
  name: wxvx
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - setuptools
    - {{ python }}
  run:
    - iotaa 1.5.*
    - met2go 11.0.*
    - netcdf4 1.7.*
    - pyproj 3.7.*
    - python-eccodes 2.42.*
    - python-magic 0.4.*
    - pyyaml 6.0.*
    - requests 2.32.*
    - seaborn 0.13.*
    - uwtools 2.12.*
    - xarray 2025.1.*
    - zarr 3.1.*
    - {{ python }}
test:
  requires:
    - docformatter 1.7.*
    - jq 1.8.*
    - make 4.4.*
    - mypy 1.19.*
    - pandas-stubs
    - pyfakefs 5.10.*
    - pytest 9.0.*
    - pytest-cov 7.0.*
    - pytest-randomly 3.15.*
    - pytest-xdist 3.8.*
    - ruff 0.14.*
    - types-PyYAML
    - types-requests
    - types-seaborn
    - {{ python }}
about:
  license: APACHE
