{% set info = load_file_data("wxvx/resources/info.json") %}
{% set python = "python 3.13" %}

package:
  name: wxvx
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - setuptools
    - {{ python }}
  run:
    - iotaa >=1.3,<1.4
    - met2go 11.0.*
    - netcdf4 >=1.7,<2
    - pyproj 3.7.*
    - python-eccodes 2.42.*
    - python-magic 0.4.*
    - pyyaml 6.0.*
    - requests >=2.32,<3
    - seaborn 0.13.*
    - uwtools >=2.8,<=2.10
    - xarray >=2023.12,<2025.2
    - zarr >=3.0,<3.1
    - {{ python }}
test:
  requires:
    - docformatter 1.7.*
    - jq 1.8.*
    - make 4.4.*
    - mypy 1.18.*
    - pyfakefs 5.9.*
    - pytest 8.4.*
    - pytest-cov 7.0.*
    - pytest-xdist 3.8.*
    - ruff 0.13.*
    - {{ python }}
about:
  license: APACHE
